import type { RecurrenceRule } from './recurrence';
import type { CreditCardTransactionKind } from './creditCard';

/** Credit Cards' "what if" scenario planner — same role and idiom as
 * `PlannedBankTransaction`/`PlannedCashEntry` (a plan stays around after
 * being marked done, flagged `executed`, independent of the real
 * `CreditCardTransaction` it created). Built specifically to close a real
 * gap: Subscriptions' own "Link to a paying account" feature only ever
 * offered Bank/Cash as a payer, with no way to say "this renews on my
 * card" — see Subscriptions' `sourceSubscriptionId` usage below.
 *
 * Deliberately mirrors the REAL `CreditCardTransaction`'s own convention
 * (`amount` always positive, `kind` decides the effect on what's owed —
 * see that type's doc comment), not `PlannedBankTransaction`'s signed
 * amount — a planned card entry is still fundamentally "log one of these 5
 * kinds of event," same as the real ledger, not a plain deposit/
 * withdrawal. */
export interface PlannedCreditCardTransaction {
  id: string;
  cardId: string;
  date: string;
  description: string;
  /** Always positive — see this type's own doc comment. */
  amount: number;
  kind: CreditCardTransactionKind;
  category?: string;
  /** True once "Mark as done" created a real `CreditCardTransaction` from
   * this plan. Only meaningful when `recurrence` is unset. */
  executed?: boolean;
  /** Same recurrence mechanism as `PlannedBankTransaction`/
   * `PlannedCashEntry` — `date` stays equal to `recurrence.startDate` when
   * set. */
  recurrence?: RecurrenceRule;
  executedThrough?: string;
  /** Exact completed dates, including occurrences fulfilled early or out of order. */
  completedDates?: string[];
  /** Parent series for a persisted, fulfilled occurrence snapshot. */
  seriesId?: string;
  /** Actual payment date when the scheduled occurrence was fulfilled early. */
  fulfilledDate?: string;
  /** Set when this plan was auto-generated by Subscriptions' "Generate
   * renewal plans" (paying via a card) rather than typed in by hand — lets
   * re-linking find and replace this subscription's own previously-
   * generated, not-yet-executed plans instead of piling up duplicates.
   * Same field name/meaning as `PlannedBankTransaction.sourceSubscriptionId`. */
  sourceSubscriptionId?: string;
}

export interface PlannedCreditCardSettings {
  /** Same display-preference pair as `PlannedBankSettings`/
   * `PlannedCashSettings`. */
  showRealBalance: boolean;
  showPlannedBalance: boolean;
}

export interface PlannedCreditCardWorkbook {
  settings: PlannedCreditCardSettings;
  entries: PlannedCreditCardTransaction[];
}
