import type { RecurrenceRule } from './recurrence';

/** User request 2026-08-23: the Banking equivalent of `types/plannedCash.ts`
 * — a "what if I spend on this" scenario planner. See that file's doc
 * comment for the full reasoning (mirrors the QSE/PSX Trade Planner
 * pattern: a plan stays around after being marked done, flagged
 * `executed`, independent of the real transaction it created), including
 * the 2026-09-07 recurrence addition (`recurrence`/`executedThrough`,
 * identical meaning here — `date` stays equal to `recurrence.startDate`
 * when set). */
export interface PlannedBankTransaction {
  id: string;
  accountId: string;
  date: string;
  description: string;
  /** Signed, same convention as `BankTransaction.amount`: negative =
   * planned debit/spend, positive = planned credit/deposit. */
  amount: number;
  category?: string;
  /** True once "Mark as done" created a real `BankTransaction` from this
   * plan. Only meaningful when `recurrence` is unset. */
  executed?: boolean;
  /** See `PlannedCashEntry`'s doc comment — identical meaning. */
  recurrence?: RecurrenceRule;
  executedThrough?: string;
  /** Exact completed dates, including occurrences fulfilled early or out of order. */
  completedDates?: string[];
  /** Parent series for a persisted, fulfilled occurrence snapshot. */
  seriesId?: string;
  /** Actual payment date when the scheduled occurrence was fulfilled early. */
  fulfilledDate?: string;
  /** Set when this plan was auto-generated by EMI/Loans' "Link to bank"
   * feature (README item 37) rather than typed in by hand — lets
   * re-linking find and replace this loan's previously-generated,
   * not-yet-executed plans instead of piling up duplicates. */
  sourceEmiLoanId?: string;
  /** The specific 1-indexed schedule month this plan represents, set
   * alongside `sourceEmiLoanId` — lets the Schedule table's Paid/Upcoming/
   * Planned status (2026-08-26) match a row to its plan exactly, instead of
   * comparing computed due-date strings (which can drift out of sync if the
   * loan's `paymentDayOfMonth` changes after the plan was generated). */
  sourceEmiMonth?: number;
  /** Same idea as `sourceEmiLoanId`, for Subscriptions' "Generate renewal
   * plans" (README item 24) — lets regeneration replace only this
   * subscription's own not-yet-executed plans. */
  sourceSubscriptionId?: string;
}

export interface PlannedBankSettings {
  /** Same display-preference pair as `PlannedCashSettings` — see that
   * file's doc comment. */
  showRealBalance: boolean;
  showPlannedBalance: boolean;
}

export interface PlannedBankWorkbook {
  settings: PlannedBankSettings;
  entries: PlannedBankTransaction[];
}
